export { default as Photogrid} from './grid/PhotoGrid'
export { default as Navbar} from './navbar/Navbar'
export { default as Hero} from './hero/Hero'
export { default as Skills} from './skills/Skills'
export { default as Project} from './project/Project'
export {default as Education} from './education/Education'
export {default as Hireme} from './hireme/Hireme'
export {default as Footer} from './footer/Footer'
